In [5]:
import os
os.chdir(path=r"C:\Users\Ion\Documents\working now\job\datascientist\rakuten_project")
os.getcwd()

'C:\\Users\\Ion\\Documents\\working now\\job\\datascientist\\rakuten_project'

In [10]:
display(os.listdir())
display(os.listdir("images"))
display(os.listdir("images/image_train")[:10])

['images',
 'images.zip',
 'Rakuten.docx',
 'X_test_update.csv',
 'X_train_update.csv',
 'Y_train_CVw08PX.csv']

['image_test', 'image_train']

['image_1000076039_product_580161.jpg',
 'image_1000089455_product_348990858.jpg',
 'image_1000092894_product_353108104.jpg',
 'image_1000093804_product_343306951.jpg',
 'image_1000095646_product_344209267.jpg',
 'image_1000095647_product_148177050.jpg',
 'image_1000099971_product_352683003.jpg',
 'image_1000100220_product_352601770.jpg',
 'image_1000222973_product_351172420.jpg',
 'image_1000228891_product_355017693.jpg']

In [12]:
import pandas as pd

X_train = pd.read_csv("X_train_update.csv")
Y_train = pd.read_csv("Y_train_CVw08PX.csv")
X_test = pd.read_csv("X_test_update.csv")

print("X_train shape:", X_train.shape)
print("Y_train shape:", Y_train.shape)
print("X_test shape:", X_test.shape)

display(X_train.head())
display(Y_train.head())

display(X_train.info())
display(X_train.describe(include="all"))

X_train shape: (84916, 5)
Y_train shape: (84916, 2)
X_test shape: (13812, 5)

,Unnamed: 0,designation,description,productid,imageid
0,0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,3804725264,1263597046
1,1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,436067568,1008141237
2,2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,201115110,938777978
3,3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,50418756,457047496
4,4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,278535884,1077757786

   Unnamed: 0  prdtypecode
0           0           10
1           1         2280
2           2           50
3           3         1280
4           4         2705

<class 'pandas.DataFrame'>
RangeIndex: 84916 entries, 0 to 84915
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   84916 non-null  int64
 1   designation  84916 non-null  str
 2   description  55116 non-null  str
 3   productid    84916 non-null  int64
 4   imageid      84916 non-null  int64
dtypes: int64(3), str(2)
memory usage: 3.2 MB

None

,Unnamed: 0,designation,description,productid,imageid
count,84916.000000,84916,55116,8.491600e+04,8.491600e+04
unique,NaN,82265,47506,NaN,NaN
top,NaN,5d Broderie Peintures Strass Diamant Bricolage...,<br>Attention !!! Ce produit est un import si...,NaN,NaN
freq,NaN,76,252,NaN,NaN
mean,42457.500000,NaN,NaN,2.555468e+09,1.152691e+09
std,24513.282066,NaN,NaN,1.588656e+09,1.751427e+08
min,0.000000,NaN,NaN,1.839120e+05,6.728400e+04
25%,21228.750000,NaN,NaN,6.760519e+08,1.056269e+09
50%,42457.500000,NaN,NaN,3.190506e+09,1.213354e+09
75%,63686.250000,NaN,NaN,3.995599e+09,1.275646e+09
max,84915.000000,NaN,NaN,4.252012e+09,1.328824e+09

In [13]:
df = pd.merge(X_train, Y_train, on="Unnamed: 0")

print(df.shape)
df.head()

(84916, 6)

,Unnamed: 0,designation,description,productid,imageid,prdtypecode
0,0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,3804725264,1263597046,10
1,1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,436067568,1008141237,2280
2,2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,201115110,938777978,50
3,3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,50418756,457047496,1280
4,4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,278535884,1077757786,2705

In [ ]:
df["prdtypecode"].nunique()

27

In [19]:
df["prdtypecode"].value_counts().head(10)

prdtypecode
2583    10209
1560     5073
1300     5045
2060     4993
2522     4989
1280     4870
2403     4774
2280     4760
1920     4303
1160     3953
Name: count, dtype: int64

In [20]:
df["prdtypecode"].describe()

count    84916.000000
mean      1773.219900
std        788.179885
min         10.000000
25%       1281.000000
50%       1920.000000
75%       2522.000000
max       2905.000000
Name: prdtypecode, dtype: float64

In [1]:
import matplotlib.pyplot as plt

df["prdtypecode"].value_counts().head(20).plot(kind="bar")
plt.title("Top 20 most frequent product categories")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'